name: Deploy React App

on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install modules
        run: |
          cd client
          npm install
      - name: Build dist
        run: |
          cd client
          npm run build
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload dist folder
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./client/dist"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
